### PR TITLE
[Improvement] Improved error handling and removed deprecated API calls

### PR DESCRIPTION
**Pull request by bwolkerstorfer**
I have added transparent logic to extract the error messages provided by LingoHub when something goes wrong while communicating with the API. These messages are required for the support to be able to help with issues.

Changes:
* removed deprecated API calls
* added logic to extract the error message provided by Lingohub when uploading and downloading

### CODE REVIEW

**Comment by bwolkerstorfer** [comment]
There is currently an issue at LingoHub with the API. The issue has been reported to the support and they are working on it.

**Comment by saxx** [comment]
Thanks for the PR. Can you take a look at the failed build, one of the tests seems to fail?
https://ci.appveyor.com/project/saxx/saxx-lingohubclient/build/1.0.0.7

**Comment by bwolkerstorfer** [comment]
The build fails because of the issue at LingoHub, we will have to trigger the build once the API is fixed. Christian from LH is already working on fixing the API endpoint.

**Comment by saxx** [comment]
Ah, now I get it. Ping me when it's fixed, then I'll retrigger the builds.

**Comment by bwolkerstorfer** [comment]
@saxx API has been fixed and tests should go through - at least they do on my local installation.

**Comment by saxx** [comment]
Hmm, new build still fails :( See https://ci.appveyor.com/project/saxx/saxx-lingohubclient 
Problem with CI server, or problem with code?

**Comment by bwolkerstorfer** [comment]
The `System.UriFormatException : Invalid URI: The format of the URI could not be determined.` exceptions that are thrown in tests are related to the deprecation/removal of the translations API endpoint as the API returns `"href": "discontinued"` for the `"rel": "translations"` in the call `GET /v1/:account/projects/:project` (https://lingohub.com/documentation/developers/api_v1/project/)

I removed the deprecated code and the related tests on my branch with the commit 875596f. The CI server is still executing the removed tests from the master branch.

**Comment by saxx** [comment]
Ah, the problem was in layer 8: Me using AppVeyor. Everything's green now, thanks. The latest artifacts should be available on AppVeyor.

**Comment by dt-bwolkerstorfer** [comment]
Awesome! Thanks!

**Pull request merged**
